name: Release

permissions: write-all

on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install release dependencies
        run: |
          npm install semantic-release@^24 \
          @semantic-release/git@^10 semantic-release-factorio@^1.5.1 \
          conventional-changelog-conventionalcommits@^8
      - name: Run semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FACTORIO_TOKEN: ${{ secrets.FACTORIO_TOKEN }}
